### ISSUE TITLE
feature: Support Adding White-listed Tokens

### ISSUE THREAD

**Issue by ErinHales** [nomad-xyz/nomad-app#1]
EDIT:
User should be able to select from list of supported tokens. Token list model (example: Uniswap)

 - [ ] Create view
        - edit: Place under `advanced` tab
 - [ ] User clicks on + New Token and opens up "Add Token" view
 - [ ] User clicks to paste token address
 - [ ] Fetch token info from Metamask using address and network
 - [ ] Display card with token info
 - [ ] "Add Token" adds it to User's token list which will be saved in local storage
 - [ ] User's tokens are displayed among default tokens in "Token Select" view
 - [ ] Show alert if user tries to add blacklisted token
 - [ ] Validate address + make sure network is selected. Disable button if not valid.
 - [ ] Track in Sentry, so we can see what tokens folks want that aren't supported by default
 
![image](https://user-images.githubusercontent.com/36751902/147697406-432c8039-59a6-4917-bf31-0203fcef1037.png)

![image](https://user-images.githubusercontent.com/36751902/147697421-d341ce97-ad52-4711-b389-e119fd0ffe3d.png)

**Comment by ErinHales** [comment]
Take a look at the Token list model (eg Uniswap)

**Comment by ErinHales** [comment]
![image](https://user-images.githubusercontent.com/36751902/166709965-f819ee11-8d6e-4412-877a-4506c789f59e.png)
https://files.slack.com/files-pri/T02DWNHUZGE-F03CSBZ8U8P/screen_shot_2022-04-27_at_11.06.21_am.png

TODO: Check with Wandi if we have designs for this yet
