### ISSUE TITLE
Error Audit

### ISSUE THREAD

**Issue by ErinHales** [nomad-xyz/nomad-app#330]
- [x] List out error cases
 - [x] Copy, what do we display to user?
 - [x] Sift through Sentry
 - [ ] How do we flag concerning errors/detect regression
